<?php

/**
 * @file
 * Provides functionality for the Digital module.
 *
 * @copyright Copyright (C) 2026 Adrian Zalewski
 * @license GPL-2.0-or-later
 */

use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_theme().
 */
function digital_theme() {
  return [
    'digital_block' => [
      'variables' => [
        'custom_data' => [],
        'custom_string' => '',
      ],
    ],
    'digital_title_block' => [
      'variables' => [
        'digital_description_string' => '',
        'custom_string' => '',
      ],
    ],
    'digital_copyright_block' => [
      'variables' => [
        'sitename_string' => '',
        'date_string' => '',
      ],
    ],
  ];
}

